data:extend(
{
    {
      type = "fluid",
      name = "planetaris-infected-water",
      subgroup = "fluid",
      icon = "__planetaris-tellus__/graphics/icons/fluids/infected-water.png",
      icon_size = 64,
      order = "g[tellus]-a",
      default_temperature = 10,
      max_temperature = 100,
      heat_capacity = "200J",
      base_color = {74, 42, 10},
      flow_color = {74, 42, 10},
    },
    {
      type = "fluid",
      name = "planetaris-chlorophyll",
      subgroup = "fluid",
      icon = "__planetaris-tellus__/graphics/icons/fluids/chlorophyll.png",
      icon_size = 64,
      order = "g[tellus]-b",
      default_temperature = 10,
      max_temperature = 100,
      heat_capacity = "200J",
      fuel_value = "1MJ",
      base_color = {8, 64, 6},
      flow_color = {8, 64, 6},
    },
    {
      type = "fluid",
      name = "planetaris-bacteriochlorophyll",
      subgroup = "fluid",
      icon = "__planetaris-tellus__/graphics/icons/fluids/bacteriochlorophyll.png",
      icon_size = 64,
      order = "g[tellus]-d",
      default_temperature = 10,
      max_temperature = 100,
      heat_capacity = "200J",
      fuel_value = "2MJ",
      base_color = {141, 23, 150},
      flow_color = {141, 23, 150},
    },
    {
      type = "fluid",
      name = "planetaris-seed-compound",
      subgroup = "fluid",
      icon = "__planetaris-tellus__/graphics/icons/fluids/seed-compound.png",
      icon_size = 64,
      order = "g[tellus]-c",
      default_temperature = 10,
      max_temperature = 100,
      heat_capacity = "200J",
      base_color = {224, 212, 135},
      flow_color = {224, 212, 135},
    },
}
)